const PRODUCT_CATALOG = [
  {
    id: "LS-01",
    name: "从雪山到日光城",
    routeCode: "达巴巴拉拉",
    destination: "lhasa",
    line: "拉萨环线",
    nights: 5,
    forms: ["自由行", "主题团"],
    seasons: [3, 4, 5, 6, 7, 8, 9, 10],
    tags: ["自然", "人文", "雪山", "经典", "首访西藏"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: true,
    description: "南迦巴瓦、巴松措、拉萨串联的经典入门线，兼顾风景和藏地文化。",
    highlights: ["南迦巴瓦", "巴松措", "拉萨"],
    cautions: ["布达拉宫等核心资源需提前预约", "若有外籍客人需提前核验车与导游资质"],
  },
  {
    id: "LS-02",
    name: "雪山圣湖布达拉",
    routeCode: "达达巴巴拉拉拉",
    destination: "lhasa",
    line: "拉萨环线",
    nights: 6,
    forms: ["主题团", "私享管家"],
    seasons: [3, 4, 5, 6, 7, 8, 9, 10],
    tags: ["自然", "人文", "经典", "雪山", "圣湖"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: true,
    description: "拉萨经典线中的均衡款，雪山、圣湖、布宫认知完整，适合第一次深度到访西藏。",
    highlights: ["南迦巴瓦", "巴松措", "布达拉宫"],
    cautions: ["旺季预约和资源锁定要更早", "若接送机非最近机场，车司管天数会增加"],
  },
  {
    id: "LS-03",
    name: "到拉萨及其更远方",
    routeCode: "拉拉拉拉日拉拉",
    destination: "lhasa",
    line: "拉萨环线",
    nights: 6,
    forms: ["主题团", "私享管家"],
    seasons: [4, 5, 6, 7, 8, 9, 10],
    tags: ["人文", "深度", "拉萨", "寺院", "日喀则"],
    intensity: "medium",
    familyFriendly: false,
    elderFriendly: true,
    foreignerNotes: true,
    description: "偏拉萨城市与人文深挖的路线，适合想看西藏精神核心的客群。",
    highlights: ["布达拉宫", "大昭寺", "色拉寺"],
    cautions: ["更依赖布宫和寺院预约", "人文浓度高，偏风景型客人需提前设期望"],
  },
  {
    id: "LS-04",
    name: "乃朗与拉萨古城",
    routeCode: "拉拉乃乃拉",
    destination: "lhasa",
    line: "拉萨环线",
    nights: 4,
    forms: ["主题团", "私享管家"],
    seasons: [4, 5, 6, 7, 8, 9, 10],
    tags: ["人文", "疗愈", "轻松", "拉萨"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: true,
    description: "拉萨周边更轻松的组合，适合不想频繁移动的客人。",
    highlights: ["拉萨古城", "乃朗山居"],
    cautions: ["产品信息有新旧版本，实际推荐前应核对当前执行版"],
  },
  {
    id: "LS-05",
    name: "遇见圣湖与圣城",
    routeCode: "巴巴巴拉拉",
    destination: "lhasa",
    line: "拉萨环线",
    nights: 5,
    forms: ["自由行"],
    seasons: [4, 5, 6, 7, 8, 9, 10],
    tags: ["自由行", "自然", "人文", "轻松"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: true,
    description: "偏自由行的圣湖圣城组合，适合想保留更多自主节奏的客人。",
    highlights: ["巴松措", "拉萨"],
    cautions: ["自由行按行程天数核算车司", "自由行不含管家费用"],
  },
  {
    id: "ML-01",
    name: "穿越三江并流",
    routeCode: "石石丙丙茨梅香丽",
    destination: "meili",
    line: "梅里环线",
    nights: 8,
    forms: ["主题团", "私享管家"],
    seasons: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    tags: ["自然", "经典", "长线", "梅里", "三江"],
    intensity: "high",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: false,
    description: "三江并流的重磅经典线，适合把松赞云南段一次看深看全。",
    highlights: ["石月亮", "丙中洛", "茨中", "梅里"],
    cautions: ["行程长、转场多，对体力要求更高", "旺淡季版本差异较多，推荐前需核对对应月份版本"],
  },
  {
    id: "ML-02",
    name: "探秘三江",
    routeCode: "塔石石丙丙梅香",
    destination: "meili",
    line: "梅里环线",
    nights: 6,
    forms: ["主题团", "私享管家"],
    seasons: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    tags: ["自然", "徒步", "三江", "经典"],
    intensity: "high",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: false,
    description: "三江产品里辨识度很高的一条，兼顾地貌层次和高山牧场体验。",
    highlights: ["塔城", "石月亮", "丙中洛", "梅里"],
    cautions: ["不同季节活动版本变化明显", "山路和转场体验需提前沟通"],
  },
  {
    id: "ML-03",
    name: "天人之际",
    routeCode: "奔奔梅梅香",
    destination: "meili",
    line: "梅里环线",
    nights: 5,
    forms: ["主题团", "自由行"],
    seasons: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    tags: ["自然", "梅里", "轻徒步", "经典"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: false,
    foreignerNotes: false,
    description: "梅里线里辨识度和销售接受度都比较高，节奏比超长线更友好。",
    highlights: ["奔子栏", "梅里雪山", "香格里拉"],
    cautions: ["冬季与常规版行程不同", "部分高海拔客人需要关注适应情况"],
  },
  {
    id: "ML-04",
    name: "转山寻酿",
    routeCode: "塔茨茨奔香",
    destination: "meili",
    line: "梅里环线",
    nights: 5,
    forms: ["主题团", "私享管家"],
    seasons: [1, 2, 3, 4, 5, 9, 10, 11],
    tags: ["人文", "自然", "葡萄酒", "文化"],
    intensity: "medium",
    familyFriendly: false,
    elderFriendly: true,
    foreignerNotes: false,
    description: "把滇藏葡萄酒文化和三江人文地理结合在一起，适合偏文化型客人。",
    highlights: ["塔城", "茨中", "奔子栏"],
    cautions: ["部分版本按季节切换", "更适合接受文化讲解型行程的客人"],
  },
  {
    id: "ML-05",
    name: "怒江漫生活",
    routeCode: "石丙丙石保",
    destination: "meili",
    line: "梅里环线",
    nights: 5,
    forms: ["私享管家"],
    seasons: [3, 4, 5, 9, 10, 11],
    tags: ["小众", "怒江", "慢节奏", "风景"],
    intensity: "medium",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: false,
    description: "更偏慢节奏和小众地貌体验，适合不想走最主流线路的客人。",
    highlights: ["石月亮", "丙中洛", "保山"],
    cautions: ["较依赖客户接受小众路线", "交通衔接和车程感知需要提前沟通"],
  },
  {
    id: "SG-01",
    name: "回到远方的家",
    routeCode: "丽丽塔塔绿绿",
    destination: "shangri-la",
    line: "香格里拉环线",
    nights: 6,
    forms: ["自由行", "主题团", "私享管家"],
    seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    tags: ["轻松", "度假", "自然", "家庭友好"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: false,
    description: "节奏舒展、综合接受度高，适合想体验松赞云南段但不想太辛苦的客人。",
    highlights: ["丽江", "塔城", "绿谷"],
    cautions: ["若第一天或最后一天仅接送机，三店有接送机豁免规则", "会员升级与实时房态需单独判断"],
  },
  {
    id: "SG-02",
    name: "亚丁的远山",
    routeCode: "丽香香亚亚亚",
    destination: "shangri-la",
    line: "香格里拉环线",
    nights: 6,
    forms: ["主题团", "私享管家"],
    seasons: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    tags: ["自然", "神山", "亚丁", "摄影"],
    intensity: "medium",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: false,
    description: "冲着亚丁神山和高原风景去的客人会很容易被打动。",
    highlights: ["丽江", "香格里拉", "亚丁"],
    cautions: ["高海拔和景区行走强度需提前管理预期"],
  },
  {
    id: "SG-03",
    name: "初探亚丁三神山",
    routeCode: "丽香亚亚香",
    destination: "shangri-la",
    line: "香格里拉环线",
    nights: 5,
    forms: ["自由行"],
    seasons: [1, 2, 3, 4, 5, 9, 10, 11],
    tags: ["自由行", "自然", "亚丁", "经典"],
    intensity: "medium",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: false,
    description: "亚丁方向相对更轻量的自由行版本，适合要自由节奏的高景观客群。",
    highlights: ["香格里拉", "亚丁"],
    cautions: ["自由行不含管家", "亚丁景区门票和身体承受能力要前置沟通"],
  },
  {
    id: "SG-04",
    name: "古道的印迹",
    routeCode: "丽泸泸亚亚亚",
    destination: "shangri-la",
    line: "香格里拉环线",
    nights: 6,
    forms: ["私享管家"],
    seasons: [3, 4, 5, 9, 10],
    tags: ["私享", "人文", "古道", "泸沽湖", "亚丁"],
    intensity: "medium",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: false,
    description: "更适合想要私密感和差异化线路体验的客人。",
    highlights: ["丽江", "泸沽湖", "亚丁"],
    cautions: ["更适合明确偏好非标路线的客人", "转场不算少"],
  },
  {
    id: "BC-01",
    name: "探索生命的力量",
    routeCode: "波波来来波达达",
    destination: "glacier",
    line: "冰川环线",
    nights: 7,
    forms: ["主题团", "私享管家"],
    seasons: [3, 4, 5, 6, 7, 8, 9, 10],
    tags: ["桃花", "冰川", "经典", "林芝", "雪山"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: false,
    foreignerNotes: true,
    description: "林芝冰川和南迦巴瓦的代表线，春季桃花和高景观非常强。",
    highlights: ["波密", "来古", "南迦巴瓦"],
    cautions: ["桃花季资源会很紧", "外籍客人要注意西藏证照与执行资质"],
  },
  {
    id: "BC-02",
    name: "最美四百公里",
    routeCode: "波波来波达",
    destination: "glacier",
    line: "冰川环线",
    nights: 5,
    forms: ["自由行"],
    seasons: [3, 4, 5, 6, 7, 8, 9, 10],
    tags: ["自由行", "冰川", "经典", "风景"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: false,
    foreignerNotes: true,
    description: "更易成交的林芝短线自由行，风景冲击力强，适合首次看林芝。",
    highlights: ["波密", "来古", "南迦巴瓦"],
    cautions: ["标准里程外异地接送另计或按政策收费", "桃花季价格波动和资源紧张明显"],
  },
  {
    id: "BC-03",
    name: "探访莲花秘境",
    routeCode: "波波墨波达",
    destination: "glacier",
    line: "冰川环线",
    nights: 5,
    forms: ["自由行"],
    seasons: [4, 5, 6, 7, 8, 9, 10],
    tags: ["自由行", "小众", "墨脱", "风景"],
    intensity: "high",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: true,
    description: "更小众也更有记忆点的墨脱方向，适合想避开大众路线的客人。",
    highlights: ["波密", "墨脱", "南迦巴瓦"],
    cautions: ["路况和通达性要更谨慎沟通", "不适合老人和低耐受客群"],
  },
  {
    id: "PE-01",
    name: "滇南漫时光",
    routeCode: "普普普普",
    destination: "puer",
    line: "普洱",
    nights: 4,
    forms: ["自由行", "主题团"],
    seasons: [1, 2, 3, 4, 5, 10, 11, 12],
    tags: ["轻松", "美食", "咖啡", "茶文化", "度假"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: false,
    description: "适合想要松弛感、吃喝体验和在地文化的客人，接受度很高。",
    highlights: ["普洱茶", "咖啡庄园", "慢生活"],
    cautions: ["更偏度假和风味体验，重雪山期待的客人需要调预期"],
  },
  {
    id: "PE-02",
    name: "舌尖上的滇南风味",
    routeCode: "普洱主题",
    destination: "puer",
    line: "普洱",
    nights: 4,
    forms: ["主题团"],
    seasons: [1, 2, 3, 4, 5, 10, 11, 12],
    tags: ["美食", "主题", "普洱", "文化"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: false,
    description: "食物切入非常强，适合对在地味道和生活方式有兴趣的客人。",
    highlights: ["普洱茶", "咖啡", "地方风味"],
    cautions: ["偏主题内容，不适合只看大景的客人"],
  },
  {
    id: "PE-03",
    name: "寻找珍贵风物",
    routeCode: "昆昆普普普",
    destination: "puer",
    line: "昆明+普洱",
    nights: 5,
    forms: ["主题团", "私享管家"],
    seasons: [1, 2, 3, 4, 5, 10, 11, 12],
    tags: ["昆明", "普洱", "城市", "美食", "文化"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: false,
    description: "把昆明城市感和普洱度假感串起来，适合怕高反或不走藏地线的客人。",
    highlights: ["昆明 citywalk", "普洱茶", "咖啡"],
    cautions: ["风景张力不如雪山线，卖点要放在生活方式体验上"],
  },
  {
    id: "PE-04",
    name: "滇南秘境",
    routeCode: "普普景普",
    destination: "puer",
    line: "普洱+景迈",
    nights: 4,
    forms: ["主题团", "私享管家"],
    seasons: [1, 2, 3, 4, 5, 10, 11, 12],
    tags: ["茶山", "秘境", "文化", "轻松"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: false,
    description: "适合想要更强茶山氛围和文化辨识度的客户。",
    highlights: ["景迈", "茶文化", "普洱"],
    cautions: ["更适合对茶和在地文化感兴趣的客群"],
  },
  {
    id: "CH-01",
    name: "寒假亲子·普洱",
    routeCode: "亲子普洱",
    destination: "puer",
    line: "寒假亲子",
    nights: 4,
    forms: ["私享管家", "主题团"],
    seasons: [1, 2],
    tags: ["亲子", "寒假", "轻松", "普洱"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: false,
    description: "更明确为亲子设计，适合假期家庭客人。",
    highlights: ["亲子体验", "普洱自然教育"],
    cautions: ["寒假季节性强", "推荐时要确认是否仍在售"],
  },
  {
    id: "CH-02",
    name: "寒假亲子·三江",
    routeCode: "亲子三江",
    destination: "meili",
    line: "寒假亲子",
    nights: 7,
    forms: ["主题团", "私享管家"],
    seasons: [1, 2],
    tags: ["亲子", "寒假", "三江", "自然"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: false,
    foreignerNotes: false,
    description: "家庭出游里景观层次更丰富的一条，适合假期深度出行。",
    highlights: ["三江", "亲子体验"],
    cautions: ["晚数长，需确认孩子体力和家庭假期长度"],
  },
  {
    id: "TH-01",
    name: "藏地桃源漫旅",
    routeCode: "波波达达百百",
    destination: "glacier",
    line: "桃花节",
    nights: 6,
    forms: ["主题团", "私享管家"],
    seasons: [3, 4],
    tags: ["桃花季", "林芝", "百巴", "春季"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: false,
    foreignerNotes: true,
    description: "春季销售爆发力很强，适合目标明确想看桃花和高景观的客人。",
    highlights: ["波密桃花", "南迦巴瓦", "百巴"],
    cautions: ["季节性极强，资源紧张", "价格更敏感，需要尽早锁单"],
  },
  {
    id: "TH-02",
    name: "雪域桃花秘境",
    routeCode: "波波来来波达达",
    destination: "glacier",
    line: "桃花节",
    nights: 7,
    forms: ["主题团", "私享管家"],
    seasons: [3, 4],
    tags: ["桃花季", "林芝", "冰川", "春季"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: false,
    foreignerNotes: true,
    description: "桃花季里更完整的林芝线，适合把桃花和冰川都吃满的客户。",
    highlights: ["波密", "来古", "南迦巴瓦"],
    cautions: ["档期和资源竞争激烈", "接待节奏要尽量早确认"],
  },
  {
    id: "DJ-01",
    name: "藏东南秘境寻花",
    routeCode: "波波百巴巴",
    destination: "glacier",
    line: "杜鹃季",
    nights: 5,
    forms: ["主题团", "私享管家"],
    seasons: [4, 5, 6],
    tags: ["杜鹃季", "藏东南", "花季", "小众"],
    intensity: "medium",
    familyFriendly: true,
    elderFriendly: false,
    foreignerNotes: true,
    description: "适合春末初夏错峰出行、追求花季景观的客人。",
    highlights: ["花季", "藏东南", "百巴"],
    cautions: ["对花期判断有一定不确定性"],
  },
  {
    id: "DJ-02",
    name: "滇西北山野之春",
    routeCode: "丽塔奔香香",
    destination: "shangri-la",
    line: "杜鹃季",
    nights: 4,
    forms: ["主题团", "私享管家"],
    seasons: [4, 5],
    tags: ["杜鹃季", "滇西北", "短线", "春季"],
    intensity: "light",
    familyFriendly: true,
    elderFriendly: true,
    foreignerNotes: false,
    description: "适合假期不长、但想在春季迅速成交的短线产品。",
    highlights: ["丽江", "塔城", "香格里拉"],
    cautions: ["更适合季节性窗口销售"],
  },
  {
    id: "LC-01",
    name: "飞向藏地桃花源",
    routeCode: "低空西藏",
    destination: "glacier",
    line: "低空旅行",
    nights: 4,
    forms: ["私享管家"],
    seasons: [3, 4, 5, 6, 9, 10],
    tags: ["低空", "高端", "稀缺", "西藏"],
    intensity: "light",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: true,
    description: "高端稀缺款，适合预算充足、强调效率与独特性的客户。",
    highlights: ["直升机/低空", "高端私享"],
    cautions: ["资源与天气限制更强", "需要更强预算承接"],
  },
  {
    id: "LC-02",
    name: "飞跃三江·神川KORA",
    routeCode: "低空云南",
    destination: "meili",
    line: "低空旅行",
    nights: 5,
    forms: ["私享管家"],
    seasons: [3, 4, 5, 6, 9, 10],
    tags: ["低空", "高端", "云南", "稀缺"],
    intensity: "light",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: false,
    description: "云南方向的高端低空产品，更适合稀缺体验型客人。",
    highlights: ["三江", "低空体验"],
    cautions: ["对天气和资源要求较高", "通常不是价格敏感客户的选择"],
  },
  {
    id: "ZT-01",
    name: "马背上的波密",
    routeCode: "马背波密",
    destination: "glacier",
    line: "主题产品",
    nights: 4,
    forms: ["私享管家"],
    seasons: [5, 6, 7, 8, 9, 10],
    tags: ["马背", "主题", "户外", "波密"],
    intensity: "high",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: true,
    description: "主题感极强，适合明确想要户外和马背体验的客人。",
    highlights: ["波密", "白龙沟牧场", "马背穿越"],
    cautions: ["对体能要求较高", "客人偏好必须足够明确"],
  },
  {
    id: "ZT-02",
    name: "马背上的香格里拉",
    routeCode: "马背哈巴",
    destination: "shangri-la",
    line: "主题产品",
    nights: 4,
    forms: ["私享管家"],
    seasons: [5, 6, 7, 8, 9, 10],
    tags: ["马背", "主题", "户外", "哈巴"],
    intensity: "high",
    familyFriendly: false,
    elderFriendly: false,
    foreignerNotes: false,
    description: "适合热爱户外、想要更鲜明主题体验的高意向客户。",
    highlights: ["哈巴古道", "马背体验"],
    cautions: ["不适合轻松型和老人儿童客群"],
  },
];
